[package]
name = "bevy_text_popup"
version = "0.3.0"
edition = "2021"
description = "Easily create temporary text pop-up nodes in the Bevy game engine"
license = "MIT OR Apache-2.0"
repository = "https://github.com/edouardpoitras/bevy_text_popup"

[dependencies]
bevy = "0.13.0"
